require("mason-lspconfig").setup({
    ensure_installed = {
        "lua_ls",
        "rust_analyzer",
        "terraformls",
        "yamlls",
        "sqls",
        "pyright",
        "buf_ls",
        "marksman",
        "eslint",
        "html",
        "gopls",
        "dockerls",
        "docker_compose_language_service",
        "cssls",
        "bashls",
        "awk_ls",
        "ansiblels",
        "jinja_lsp",
        "clangd",
        "helm_ls",
        "just",
    },
    automatic_enable = {
        exclude = { "clangd" },
    },
})
