#!/usr/bin/env bash

set -o pipefail

opencmd="${BROWSER:-"xdg-open"}"

if [[ "$(uname)" == "Darwin" ]]; then
	opencmd=open
fi

PROMPT_PROGRAM="command fzf --reverse --prompt \"Bookmarks > \" --cycle"
if [[ "$1" == "dmenu" ]]; then
	PROMPT_PROGRAM="dmenu -i -l 15 -p \"Bookmarks\""
fi

BOOKMARKS_FILE="$HOME/.local/share/bookmarks"
if [[ "$1" == "edit" ]]; then
	"${EDITOR:-"vim"}" "$BOOKMARKS_FILE"
	exit
fi

while true; do
	valid_bookmarks=$(grep -oE '^.+[[:space:]]https?://[^[:space:]]+[[:space:]]*$' "$BOOKMARKS_FILE")
	names=$(sed -E 's/[[:space:]]https?:\/\/([^\/]+).*$/ (\1)/' <<<"$valid_bookmarks" | sed -E 's/www\.(.+\))$/\1/')
	choice=$(echo "$names" | eval "$PROMPT_PROGRAM")
	[[ -z "$choice" ]] && exit

	website_name=$(sed -E 's/[[:space:]]\([^()]+\)$//' <<<"$choice" | sed -E 's/([+?|^$\\().*{}])/\\\1/g')
	link=$(grep -E "^$website_name[[:space:]]https?://[^[:space:]]+[[:space:]]*$" "$BOOKMARKS_FILE" | head -1 | sed -E -e 's/^[[:space:]]+|[[:space:]]+$//' -e 's/.+[[:space:]]([^[:space:]]+)$/\1/')
	[[ $? -eq 1 ]] && exit 1

	$opencmd "$link" &>/dev/null &
	disown
	[[ "$1" == "dmenu" || "$1" == "exit" ]] && break
done
