#!/usr/bin/env bash

set -o errexit
set -o pipefail

WALLPAPERS_PATH="$HOME/.local/share/wallpapers"
WALLPAPER_DEST="$HOME/.local/share/bg"

PROMPT_PROGRAM="dmenu -i -l 15 -p \"Choose wallpaper\""
if [[ -t 1 && -t 0 ]]; then
	PROMPT_PROGRAM="gum filter --header \"Choose wallpaper\""
fi

choice="$(find "$WALLPAPERS_PATH" -maxdepth 1 \
	-iname '*.png' -o \
	-iname '*.jpg' -o \
	-iname '*.jpeg' | sort | sed -E 's/.*\/([^\/]+)$/\1/' |
	eval "$PROMPT_PROGRAM")"

cp "$WALLPAPERS_PATH/$choice" "$WALLPAPER_DEST"

case $XDG_SESSION_TYPE in
"wayland")
	if [[ -x "$(command -v swaybg)" ]]; then
		pkill swaybg
		nohup swaybg -m fill -i "$WALLPAPER_DEST" &>/dev/null &
	fi
	;;
"x11")
	if [[ -x "$(command -v feh)" ]]; then
		feh --no-fehbg --bg-fill "$WALLPAPER_DEST"
	fi
	;;
esac
