#!/bin/bash

set -o errexit
set -o pipefail

if [[ -n "$TMUX" ]]; then
	echo "You are in a tmux session"
	exit 1
fi

sessions_raw="$(tmux ls -F \#S 2>/dev/null || true)"
if [[ -z "$sessions_raw" ]]; then
	echo "No active tmux sessions"
	exit 1
fi
IFS=$'\n' mapfile -t sessions <<<"$sessions_raw"
session="$(gum choose --header "Choose what tmux session attach to" "${sessions[@]}")"
tmux attach -t "$session"
