#!/bin/bash

set -o errexit
set -o pipefail

if [[ -n "$TMUX" ]]; then
	echo "You are in a tmux session"
	exit 1
fi

sessions_raw="$(tmux ls -F \#S 2>/dev/null || true)"
if [[ -z "$sessions_raw" ]]; then
	echo "No active tmux sessions"
	exit 1
fi

# sessions=()
# while read -r line; do
# 	sessions+=("$line")
# done <<< "$sessions_raw"

session="$(IFS=$'\n'; gum choose --header "Choose what tmux session attach to" $sessions_raw)"
tmux attach -t "$session"
