#!/usr/bin/env bash

set -euo pipefail
s="$(find "$HOME/Projects" -mindepth 1 -maxdepth 1 -type d | awk -F/ '{print $NF}' | command fzf)"
session_name=$(tr '.' '_' <<<$s)
tmux new -c "$HOME/Projects/$s" -s "$session_name" || tmux attach -t "$session_name"
