live_config_reload = true

import = [
	"~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 25
y = 20

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
