theme = "custom"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
g = { c = "code_action" }
K = "hover"
space = { f = { f = "file_picker" }, p = { v = "file_explorer" } }

[keys.insert]
esc = ["collapse_selection", "normal_mode", "move_char_left"]
