theme = "tokyonight_custom"

[editor]
line-number = "relative"
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
g = { c = "code_action" }
K = "hover"

[editor.cursor-shape]
insert = "bar"
